//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIEI.Models
{
    using System;
    using System.Collections.Generic;
    using SIEI.Capas.Capa_Entidad;


    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Requerimiento = new HashSet<Requerimiento>();
            this.Telefono_Empresa = new HashSet<Telefono_Empresa>();
            this.Ubicacion = new HashSet<Ubicacion>();
        }
    
        public string identificacion { get; set; }
        public string id { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<bool> certificacion { get; set; }
        public Nullable<int> puntos { get; set; }
        public string especialidad { get; set; }

        /**/
        public Empresa(EntidadEmpresa nuevaEmpresa)
        {
            identificacion = nuevaEmpresa.getIdentificacion;
            nombre = nuevaEmpresa.getNombre;
            id = nuevaEmpresa.getId;
        }

        public virtual Especialidad Especialidad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requerimiento> Requerimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefono_Empresa> Telefono_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ubicacion> Ubicacion { get; set; }
    }
}
