//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIEI.Models
{
    using System;
    using System.Collections.Generic;
    using SIEI.Capas.Capa_Entidad;
    using System.Web.Providers.Entities;
    using Microsoft.AspNet.Identity;
    using System.Web;
    using System.IO;

    public partial class Persona
    {
        ApplicationDbContext context = new ApplicationDbContext();

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Aplica = new HashSet<Aplica>();
            this.Servicio = new HashSet<Servicio>();
            this.Telefono_Persona = new HashSet<Telefono_Persona>();
            this.Trabaja_En = new HashSet<Trabaja_En>();
        }

        /**/
        public Persona(EntidadPersona nuevaPersona)
        {
            identificacion = nuevaPersona.getIdentificacion;
            id = nuevaPersona.getId;
            correo = nuevaPersona.getCorreo;

        }

        public Persona(EntidadPersona nuevaPersona, Boolean actualizar)
        {
            
            identificacion = nuevaPersona.getIdentificacion;
            id = HttpContext.Current.User.Identity.GetUserId();
            nombre = nuevaPersona.getNombre;
            apellido1 = nuevaPersona.getApellido1;
            apellido2 = nuevaPersona.getApellido2;
            correo = nuevaPersona.getCorreo;
            discapacidad = nuevaPersona.getDiscapacidad;
            curriculo = nuevaPersona.getCurriculo;
        }

        public string identificacion { get; set; }
        public string id { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string correo { get; set; }
        public byte[] curriculo { get; set; }
        public Nullable<bool> discapacidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aplica> Aplica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio> Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefono_Persona> Telefono_Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trabaja_En> Trabaja_En { get; set; }
    }
}
