//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIEI.Models
{
    using System;
    using System.Collections.Generic;
    using SIEI.Capas.Capa_Entidad;

    public partial class Puesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Puesto()
        {
            this.Aplica = new HashSet<Aplica>();
            this.Trabaja_En = new HashSet<Trabaja_En>();
            this.Requerimiento = new HashSet<Requerimiento>();
        }
    
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string ubicacionPuesto { get; set; }
        public Nullable<int> idArea { get; set; }

        public Puesto(EntidadPuesto nuevoPuesto)
        {
            identificacion = nuevoPuesto.getIdentificacion;
            nombre = nuevoPuesto.getNombre;
            descripcion = nuevoPuesto.getDescripcion;
            ubicacionPuesto = nuevoPuesto.getUbicacionPuesto;
            idArea = nuevoPuesto.getIdArea;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aplica> Aplica { get; set; }
        public virtual Area_Trabajo Area_Trabajo { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trabaja_En> Trabaja_En { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requerimiento> Requerimiento { get; set; }
    }
}
