//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIEI.Models
{
    using System;
    using System.Collections.Generic;
    using SIEI.Capas.Capa_Entidad;
    
    public partial class Telefono_Persona
    {
        public string identificacion { get; set; }
        public string numero { get; set; }
    
        public virtual Persona Persona { get; set; }

        public Telefono_Persona(EntidadTelefono_Persona nueva)
        {
            identificacion = nueva.getIdentificacion;
            numero = nueva.getNumero;
        }

        public Telefono_Persona()
        {
        }
    }
}
