//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIEI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono_Empresa
    {
        public string identificacion { get; set; }
        public string numero { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
